apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend-5-studycompass-redis

resources:
- deployment.yaml
- service.yaml

vars:
- name: BACKEND_5_STUDYCOMPASS_REDIS_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: redis
