apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend-5-studycompass-neo4j

resources:
- deployment.yaml
- pvc.yaml
- service.yaml

vars:
- name: BACKEND_5_STUDYCOMPASS_NEO4J_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: neo4j
