apiVersion: apps/v1
kind: Deployment
metadata:
  name: "1-service-registry"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
  template:
    metadata:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: web
        image: socialcomputing/elas-official-backend-1-service-registry
        ports:
        - containerPort: 8761
        env:
        - name: PORT
          value: "8761"
        - name: HOST
          value: $(BACKEND_1_SERVICE_REGISTRY_SERVICE)
