apiVersion: v1
kind: Service
metadata:
  name: "1-service-registry"
  labels:
    app.kubernetes.io/component: "1-service-registry"
spec:
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
  selector:
    app.kubernetes.io/component: "1-service-registry"
