import React, { Component, useState } from "react";
import * as Survey from "survey-react";
import "survey-react/survey.css";
import Footer from '../Reusable/Footer';
import Results from '../Results/Results';
import '../../Intogen.css';
import * as widgets from "surveyjs-widgets";
import $ from "jquery"; 
import "easy-autocomplete/dist/easy-autocomplete.css";

Survey.StylesManager.applyTheme("orange");

class FindYourType extends Component {
  constructor(props) {
      super(props)
      window["$"] = window["jQuery"] = $;
      require("easy-autocomplete/dist/jquery.easy-autocomplete.js");
      this.model = new Survey.Model(json)
      this.state = {
        data: ""
      }
      this.onCompleteComponent = this.onCompleteComponent.bind(this)
  }

  onCompleteComponent = () => {
    this.setState({
      isCompleted: true
    })
  };

  render() {
    widgets.autocomplete(Survey);
    var surveyRender = !this.state.isCompleted ? (
      <Survey.Survey 
        model={this.model}
        json={json}
        css={myCss}
        showCompletedPage={false}
        onComplete={this.onCompleteComponent}
      />
    ) : null

    var onSurveyCompletion = this.state.isCompleted ? (
      <div>
        <Results dataR={this.model.data}/>
      </div>
    ) : null;

    return (
      <div className="App">
        <hr class="border2" data-content="Find your Type"/>
        <div className="page-container">
          <span className="subTitle">David Kolb's Learning Style <b>Questionnaire</b></span><br/>
          { surveyRender }
          { onSurveyCompletion }
        </div>
        <Footer/>
      </div>
    );
  }
}

var myCss = {
  matrix: {
    root: "table table-striped",
    rowError: "sv-matrix__row--error",
    label: "sv-item sv-radio sv-matrix__label",
    itemChecked: "sv-radio--checked",
    itemDisabled: "sv-item--disabled sv-radio--disabled",
    itemHover: "sv-radio--allowhover",
    materialDecorator: "sv-item__decorator sv-radio__decorator",
    cellText: "sv-matrix__text",
    cellTextSelected: "sv-matrix__text--checked",
  },
  radiogroup: {
    root: "sv_qcbc form-inline",
    container: "sv_container",
    body: "sv_body",
    
  }
};

const json = {
  showProgressBar: "top",
  showQuestionNumbers: "off",
  pages: [
    {
      questions: 
      [
        {
          type: "radiogroup",
          name: "",
          title: "Questions are based on David Kolb's research. This questionnaire is designed to define out your preferred learning styles(s) as an adult. Over the years, you have probably developed learning habits that help you benefit more from some experiences than from others. This questionnaire will probably take you about 7-10 minutes to complete. The accuracy of your results depends on how honest you are. There are no right or wrong answers. For each statement, choose if you would rather agree or disagree with it. If you find yourself wondering which situation to think of when answering a question, just think about how you are when you are working with people. Go with your first gut reaction instead of overthinking your response.",
        },
      ]
    }, 
    { 
      questions: [
        {
          type: "matrix",
          name: "Activist", 
          title: "Please indicate if you agree or disagree with the following statements!",
          isAllRowRequired: true,
          columns: [ 
            { value: 10, text: "Agree" }, 
            { value: 0, text: "Disagree" }
          ],    
          rows: [
            { value: "2", text: "I often act without considering the possible consequences."},
            { value: "4", text: "I often find that actions based on feelings are as sound as those based on careful thought and analysis."},
            { value: "10", text: "I am attracted more to novel, unusual ideas than to practical ones."},
            { value: "13", text: "I enjoy fun-loving spontaneous people."},
            { value: "18", text: "I prefer to respond to events in a spontaneous, flexible way rather than plan things out in advance."},
            { value: "21", text: "It is more important to enjoy the present moment than to think about the past or future."},
            { value: "24", text: "More often than not, rules are there to be broken."},
            { value: "30", text: "I enjoy being the one that talks a lot."},
            { value: "37", text: "I find the formality of having specific objectives and plans stifling."},
            { value: "39", text: "I quickly get bored with methodical, detailed work."}
          ],
        }
      ]
    }, 
    {
      questions: [
        {
          type: "matrix",
          name: "Reflector",
          title:"Good! Now please proceed as before.",
          isAllRowRequired: true,
          columns: [ 
            { value: 10, text: "Agree" }, 
            { value: 0, text: "Disagree" }
          ],
          rows: [
            { value: "5", text: "I like the sort of work where I have time for thorough preparation and implementation."},
            { value: "9", text: "I take care over how I interpret data and avoid jumping to conclusions."},
            { value: "14", text: "I pay careful attention to detail before coming to a conclusion."},
            { value: "16", text: "In discussions, I enjoy watching the plotting and scheming of the other participants."},
            { value: "17", text: "I prefer to have as many sources of information as possible - the more information to think over the better."},
            { value: "20", text: "I often get irritatetd by people who want to rush things."},
            { value: "25", text: "I prefer to stand back from a situation and consider all the perspectives."},
            { value: "29", text: "If I have a report to write, I tend to produce lots of drafts before settling on the final version."},
            { value: "33", text: "In discussions I am more likely to adopt a 'low profile' than to take the lead and do most of the talking."},
            { value: "34", text: "On balance, I do the listening rather than the talking."}
          ]
        }
      ]
    }, 
    {
      questions: [
        {
          type: "matrix",
          name: "Theorist",
          title: "Again, please choose if you would rather agree or disagree!",
          isAllRowRequired: true,
          columns: [ 
            { value: 10,  text: "Agree" }, 
            { value: 0, text: "Disagree" }
          ],
          rows: [
            { value: "1", text: "I have strong beliefs about what is right and wrong, good and bad."}, 
            { value: "6", text: "I regularly question people about their basic assumptions."},
            { value: "8", text: "I get on best with logical, analytical people and less well with spontaneous, `irrational` people." },
            { value: "11", text: "I like to relate my actions to a general principle, standard or belief."},
            { value: "15", text: "I find it difficult to produce ideas on impulse."},
            { value: "22", text: "I tend to be a perfectionist."},
            { value: "27", text: "I believe that rational, logical thinking should win the day."},
            { value: "32", text: "In discussions with people I often find I am the most dispassionate and objective."},
            { value: "35", text: "I tend to be tough on people who find it difficult to adopt a logical approach."},
            { value: "40", text: "I like meetings to be run on methodical lines, sticking to a laid down agenda."}
          ]
        }
      ]
    }, 
    {
      questions: [
        {
          type: "matrix",
          name: "Pragmatist",
          title: "Almost done! Please indicate if you agree or disagree with the presented statements.",
          isAllRowRequired: true,
          columns: [ 
            { value: 10, text: "Agree" }, 
            { value: 0, text: "Disagree" }
          ],
          rows: [
            { value: "3", text: "I have a reputation for saying what I think, simply and directly."},
            { value: "7", text: "When I hear about a new idea or approach, I immediatley start working out how to apply it in practice."},
            { value: "12", text: "In discussions, I like to get straight to the point."},
            { value: "19", text: "I tend to be attracted to techniques such as flow charts, contingency plans etc."},
            { value: "23", text: "In meetings, I put forward practical, realistic ideas."},
            { value: "26", text: "I think written reports should be short and to the point."},
            { value: "28", text: "In discussions, I get impatient with irrelevant issues and digressions."},
            { value: "31", text: "In discussions, I often find I am a realist, keeping people to the point and avoiding wild speculations."},
            { value: "36", text: "Most times I believe the end justifies the means."},
            { value: "38", text: "I do whatever is practical to get the job done."}
          ]
        }
      ]
    }, 
    {
      questions: [
        {
          type: "radiogroup",
          name: "Major",
          title: "What are you currently studying?",
          isRequired: true,
          colCount: 2,
          choices: ["Bachelor", "Master"]
        }, 
        {
          type: "dropdown",
          name: "program-bachelor",
          title: "Please choose your study program.",
          visibleIf: "{Major}=Bachelor",
          isRequired: true,
          
          choices: 
            [
              "B.Sc. Computer Engineering (Software Engineering)",
              "B.Sc. Computer Engineering (Communications)",
              "B.Sc. Electrical and Electronic Engineering",
              "B.Sc. Mechanical Engineering",
              "B.Sc. Metallurgy and Metal Forming",
              "B.Sc. Steel Technology and Metall Forming",
              "B.Sc. Structural Engineering"
            ]
        }, 
        {
          
          name: "program-master",
          title: "Please choose your study program.",
          type: "dropdown",
          visibleIf: "{Major}=Master",
          isRequired: true,
          choices: 
            [
              "M.Sc. Automation and Control Engineering",
              "M.Sc. Computer Enginerring (Intelligent Networked Systems)",
              "M.Sc. Computer Engineering (Interactive Systems and Visualization)",
              "M.Sc. Computational Mechanics",
              "M.Sc. Communications Engineering",
              "M.Sc. Embedded Systems Engineering",
              "M.Sc. Mechanical Engineering (General Mechanical Engineering)",
              "M.Sc. Mechanical Engineering (Energy and Environmental Engineering)",
              "M.Sc. Mechanical Engineering (Mechatronics)",
              "M.Sc. Mechanical Engineering (Production and Logistics)",
              "M.Sc. Mechanical Engineering (Ship and Offshore Technology)",
              "M.Sc. Metallurgy and Metal Forming",
              "M.Sc. Management and Technology of Water and Waste Water",
              "M.Sc. Power Engineering"
            ]            
        }, 
        {
          name: "most-liked-bachelor",
          title: "Please name a course which you liked the most.",
          type: "text",
          isRequired: true,
          visibleIf: "{Major}=Bachelor",
          choices: 
            [ 
              "Digitale Medien",
              "Regelungstechnik EIT (alt: Einführung in die Automatisierungstechnik)",
              "Control Engineering",
              "Werkstoffkunde Stahl",
              "Embedded Systems",
              "Mathematics I1",		
              "Theorie linearer Systeme	",
              "Mathematics I2",	
              "Mechanics I1",	
              "Baubetrieb 1",
              "Statistics for Engineers",		
              "Fertigungslehre",
              "Werkstoffe des Bauens 2",
              "Grundlagen der künstlichen Intelligenz",	
              "Fundamentals of Electrical Engineering I3",
              "Mechanics I3",		
              "Datenbanken",	
              "Werkstoffe 3",
              "Grundlagen der Bildverarbeitung",
              "Optische Übertragungstechnik",	
              "Sensorik und Aktuatorik",	
              "Umformtechnik 1",	
              "Wasserbau 1 - Wasserbauliche Planungsgrundlagen und Anlagen",
              "Wärmekraft- und Arbeitsmaschinen",
              "Umformtechnik 2",
              "Internet Technologie u. Web Engineering",
              "Grundlagen der Programmentwurfstechnik",
              "Design Theory 1",
              "Baubetrieb 2",
              "Digitale Regelung (alt: Regelungstechnik E)",			
              "Objektorientierte Programmierung",	
              "Datenstrukturen und Algorithmen",
              "Elektrische Maschinen",
              "Baustatik 2",
              "Logik",				
              "Network Analysis",	
              "Siedlungswasserwirtschaft 2",
              "Mathematik M3",		
              "Computer Based Engineering Mathematics",	
              "Grundlagen der Metallkunde 1",	
              "Baustatik 1",
              "Static and Stationary Fields",		
              "Grundlagen der Metallkunde 2",	
              "Stahlbau 3 - Stahl- und Verbundhochbau",
              "Measurement Technology	CAD (bzw. CAD/CAE)",		
              "Fundamentals of Programming",
              "Automaten und formale Sprachen (schriftlich)",		
              "Elektrische Energieversorgungssysteme",	
              "Messtechnik",		
              "Thermodynamics 1",	
              "Betonbau 3 - Grundlagen des Spannbetonbaus und des Ingenieurbaus",
              "Rechnernetze und Kommunikationssysteme",				
              "Fundamentals of Computer Engineering 1",	
              "Energietechnik",		
              "Numerische Methoden für Ingenieure",	
              "Siedlungswasserwirtschaft 1", 
              "Multimedia Systeme",			
              "Werkstoffauswahl verschleiß- und korrosionsbeständiger Werkstoffe",	
              "Elektronische Bauelemente",			
              "Werkstoffprüfung	E2", 
              "Berechnungsprogramme",
              "Mensch-Computer Interaktion",	
              "Grundlagen elektronischer Schaltungen",			
              "Theoretische Metallurgie (alt: Metallurgie)	E2", 
              "Bauinformatik 2",
              "Fortgeschrittene Programmiertechniken",	
              "Programmierparadigmen",			
              "Betriebswirtschaft für Ingenieure",	
              "Betriebssysteme",			
              "Modellbildung und Simulation",		
              "Thermodynamics 2",	
              "Grundlagen der Elektronik",				
              "Physics",	
              "Modellierung",	
              "Operating Systems and Computer Networks",				
              "Werkstofftechnik 1",	
              "Logical Design of Digital Systems",			
              "Werkstofftechnik 2",	
              "NE-Gusswerkstoffe",	
              "Computer Networks Lab",			
              "Theorie der Stahlerzeugung",	
              "Strömungslehre 2",		
              "Eisen- und Stahlerzeugung 2",	
              "Wissenschaftliches Arbeiten",	
              "Systemdynamik und Regelungstechnik Praktikum",			
              "Sprachtechnologie",					
              "Internet-Suchmaschinen",				
              "Mechanics I2"
            ]	
        }, {
            type:"rating",
            name: "gpa-most-liked-bachelor",
            visibleIf: "{Major}=Bachelor",
            title: "Please select the grade you have achieved in the course you liked the most.",
            isRequired: true,
        }, {
            name: "most-disliked-bachelor",
            title: "Please name a course which you disliked the most.",
            type: "text",
            isRequired: true,
            visibleIf: "{Major}=Bachelor",
            choices: 
            [ 
              "Digitale Medien",
              "Regelungstechnik EIT (alt: Einführung in die Automatisierungstechnik)",
              "Werkstoffkunde Stahl",
              "Embedded Systems",
              "Mathematics I1",		
              "Mechanics I2",	
              "Theorie linearer Systeme	",
              "Mathematics I2",	
              "Mechanics I1",	
              "Baubetrieb 1",
              "Statistics for Engineers",		
              "Fertigungslehre",
              "Werkstoffe des Bauens 2",
              "Grundlagen der künstlichen Intelligenz",	
              "Fundamentals of Electrical Engineering I3",
              "Mechanics I3",		
              "Datenbanken",	
              "Werkstoffe 3",
              "Grundlagen der Bildverarbeitung",
              "Optische Übertragungstechnik",	
              "Sensorik und Aktuatorik",	
              "Umformtechnik 1",	
              "Wasserbau 1 - Wasserbauliche Planungsgrundlagen und Anlagen",
              "Wärmekraft- und Arbeitsmaschinen",
              "Umformtechnik 2",
              "Internet Technologie u. Web Engineering",
              "Grundlagen der Programmentwurfstechnik",
              "Design Theory 1",
              "Baubetrieb 2",
              "Digitale Regelung (alt: Regelungstechnik E)",			
              "Objektorientierte Programmierung",	
              "Datenstrukturen und Algorithmen",
              "Elektrische Maschinen",
              "Baustatik 2",
              "Logik",				
              "Network Analysis",	
              "Siedlungswasserwirtschaft 2",
              "Mathematik M3",		
              "Computer Based Engineering Mathematics",	
              "Grundlagen der Metallkunde 1",	
              "Baustatik 1",
              "Static and Stationary Fields",		
              "Grundlagen der Metallkunde 2",	
              "Stahlbau 3 - Stahl- und Verbundhochbau",
              "Measurement Technology	CAD (bzw. CAD/CAE)",		
              "Fundamentals of Programming",
              "Automaten und formale Sprachen (schriftlich)",		
              "Elektrische Energieversorgungssysteme",	
              "Messtechnik",		
              "Thermodynamics 1",	
              "Betonbau 3 - Grundlagen des Spannbetonbaus und des Ingenieurbaus",
              "Rechnernetze und Kommunikationssysteme",				
              "Fundamentals of Computer Engineering 1",	
              "Energietechnik",		
              "Numerische Methoden für Ingenieure",	
              "Siedlungswasserwirtschaft 1", 
              "Multimedia Systeme",			
              "Werkstoffauswahl verschleiß- und korrosionsbeständiger Werkstoffe",	
              "Elektronische Bauelemente",			
              "Werkstoffprüfung	E2", 
              "Berechnungsprogramme",
              "Mensch-Computer Interaktion",	
              "Grundlagen elektronischer Schaltungen",			
              "Theoretische Metallurgie (alt: Metallurgie)	E2", 
              "Bauinformatik 2",
              "Fortgeschrittene Programmiertechniken",	
              "Programmierparadigmen",			
              "Betriebswirtschaft für Ingenieure",	
              "Betriebssysteme",			
              "Modellbildung und Simulation",		
              "Thermodynamics 2",	
              "Grundlagen der Elektronik",				
              "Physics",	
              "Modellierung",	
              "Operating Systems and Computer Networks",				
              "Werkstofftechnik 1",	
              "Logical Design of Digital Systems",			
              "Werkstofftechnik 2",	
              "NE-Gusswerkstoffe",	
              "Computer Networks Lab",			
              "Theorie der Stahlerzeugung",	
              "Strömungslehre 2",		
              "Eisen- und Stahlerzeugung 2",	
              "Wissenschaftliches Arbeiten",	
              "Systemdynamik und Regelungstechnik Praktikum",			
              "Sprachtechnologie",					
              "Internet-Suchmaschinen",				
              "Control Engineering"
            ]
           }, 
           {
            type:"rating",
            name: "gpa-most-disliked-bachelor",
            visibleIf: "{Major}=Bachelor",
            title: "Please select the grade you have achieved in the course you disliked the most.",
            isRequired: true,
           },  
           {
            name: "most-liked-master",
            title: "Please name a course which you liked the most.",
            type: "text",
            isRequired: true,
            visibleIf: "{Major}=Master",
            choices: 
            [ 
              "Modellierung nebenläufiger Systeme",	
              "Geotechnik 7 - Numerische Modellierung in der Geotechnik",		
              "Mess- und Sensorsysteme",
              "Combustion Science (nur noch Wiederholer)",	
              "Thermodynamik und Kinetik metallurgischer Reaktionen",	
              "Siedlungswasserwirtschaft 5 - Biologie und Chemie in der Siedlungswasserwirtschaft",	
              "Schaltanlagen",
              "Modellierung, Analyse, Verifikation",		
              "State and Parameter Estimation",
              "Mobilkommunikationsgeräte",
              "Manipulatortechnik",
              "Technische Schadenskunde",
              "Quality Management in Water Supply",
              "Regenerative Energietechnik 1",
              "Real-Time Systems (letztmalig im WiSe 19/20- nur noch Wiederholer)",	
              "Recommender Systeme	Advanced Numerical Methods",
              "Kommunikationsnetze	Optische Signalverarbeitung",		
              "Rechnergestützte Netzanalysen",
              "Strömungsmaschinen",
              "Testing of Metallic Materials",
              "Mechanische Verfahrenstechnik in der Wasseraufbereitung",
              "Mathematik E4",
              "Formale Spezifikation von Software-Systemen"	,
              "Geotechnik 4",
              "Bodenmechanik 2",					
              "Intermodale Distributionsnetze",
              "Regenerative Energietechnik 2",	
              "Die Methode der Finiten Elemente 1",	
              "Thermische Verfahrens- und Prozesstechnik",	
              "Advanced Computer Architecture",
              "Nonlinear Control Systems",		
              "Muster- und komponentenbasierte Software-Entwicklung",			
              "Bildsignaltechnik",				
              "Strategische Logistikplanung (alt: Außerbetrieblicher Transport)",	
              "Brennstoffzellensysteme in der dezentralen Energieversorgung",	
              "Endabmessungsnahes Gießen",	
              "Production Management",	
              "Leistungselektronik",
              "Natürlichsprachliche Mensch-Computer Interaktion",								
              "Quantitative bildgebende Messtechniken in Strömungen",	
              "Die Methode der Finiten Elemente 2",	
              "Adsorption Technology",	
              "Informationstechnik in der elektrischen Energietechnik",
              "Entwicklung sicherer Software	Continuum Mechanics",		
              "Systemtechnik (alt: Mikro- und Nanosystemtechnik)",			
              "Antriebstechnik",		
              "Fahrzeugtechnik",
              "Rechnerintegrierte Produktentwicklung CAE (Computer Aided Engineering)",	
              "Planung wassertechnischer Anlagen: Systemkomponenten, Instrumentierung und Steuerungstechnik",	
              "Netzberechnung",
              "Electronic communities and social networks",	
              "Introduction to Numerical Methods",	
              "Computer/Robot Vision	Optical Communications Technology",				
              "Fabrikplanung",		
              "Schweißtechnische Fertigungsverfahren",	
              "Energie und Umwelt",	
              "Elektromagnetische  Verträglichkeit",
              "Peer-to-Peer Systeme",	
              "Structural Dynamics	Coding Theory",	
              "Test und Zuverlässigkeit digitaler Systeme",		
              "Dampfturbinen	Fahrzeugdynamik",			
              "Konstruieren mit Guss aus Fe- und NE-Metallen",
              "Siedlungswasserwirtschaft 4 - Stadtentwässerung und Regenwasserbehandlung",	
              "Nichtstationäre Vorgänge in elektrischen Netzen",
              "Mehrgrößenregelung",			
              "Design of concrete structures",		
              "Internet of Things: Protocols and System Software",			
              "Biomechanik	Höhere Werkstofftechnik - Tribologie",		
              "Metallkunde und Metallphysik",
              "Waste Water Treatment",	
              "Theorie statistischer Signale",
              "Interaktive Systeme",		
              "Robust Control (Robuste Regelung)",				
              "Biofluidmechanik",	
              "Automobile Produktionstechnik",	
              "Tensor Calculus",
              "Thermische Abfallbehandlung",	
              "Modelling and Simulation of Dynamic Systems",
              "Cognitive Robot Systems",			
              "Numerical Mathematics",			
              "Notlauf und Diagnose mechatronischer Systeme",	
              "Informationssysteme der Logistik (alt: Logistische Informationssysteme)",	
              "Control Theory",	
              "Schwingungsanalyse metallurgischer Anlagen",	
              "Computational Fluid Dynamics (incompressible fluids)",	
              "Elektrizitätswirtschaft",
              "Advanced Mobile Communications",				
              "Modellierung von Logistiksystemen (alt: Rechnergestützte Modellierung)",	
              "Sensoren für Fortgeschrittene - Anwendungen, Schnittstellen und Signalverarbeitung",	
              "Gießen und Erstarren von Stahl",	
              "Water Treatment 2",	
              "Theoretische Elektrotechnik 1",
              "Thermodynamics of Materials",		
              "Self-Organising Embedded Systems",			
              "Kinematics of Robots and Mechanism",		
              "Verbrennungsmotoren",	
              "Werkstoffwissenschaftliche Vertiefung der Fe-Gusswerkstoffe",	
              "Water - Natural Science Fundamentals",	
              "Numerical  Mathematics",
              "Neuroinformatik und Organic Computing",	
              "Stahlbau 5 - Schalen, Türme und Masten aus Stahl",	
              "Theoretische Elektrotechnik 2",	
              "Radio Propagation Channels",			
              "Qualitative Methoden der Regelungstechnik 2: Automaten und Netze",	
              "Kunststoffmaschinen und -verarbeitung: Spritzgießtechnik",	
              "Thermische Verfahrenstechnik",	
              "Recycling of Oxidic and Metallic Materials",	
              "Wassergewinnung",	
              "Thermodynamik und Kraftwerktechnik",		
              "Game Architecture and Design",	
              "Finite Element Method - Multiphase Materials",		
              "Global Engineering",			
              "Schwingungsanalyse mit MATLAB",	
              "Virtuelle Produktdarstellung",	
              "Wärmebehandlung metallischer Werkstoffe",	
              "Management und Controlling in der Wasserversorgung und -entsorgung",	
              "Power System Operation and Control",
              "Cloud, Web&Mobile",
              "Elektronische Schaltungen",	
              "Kognitive Technische Systeme",
              "Hydrodynamik 2",
              "Plastomechanik und Umformverfahren",
              "Water Treatment 1",
              "Grundlagen der Hochspannungstechnik",
              "Computational Inelasticity",
              "Advanced System and Control Theory",
              "Hochfrequenzschaltungen und Leistungsbauelemente",	
              "Gasturbinen",
              "Additive Fertigungsverfahren 2 – Kunststoffverarbeitung",
              "Seeverhalten und hydrodynamische Belastung von Schiffen und Offshore-Anlagen",	
              "Wärme- und Stoffübertragung",
              "Membrane Technology for Water Treatment",
              "Wind Energy",
              "Prozessautomatisierung",
              "Finite Element Method Foundation",
              "Microwave Theory and Techniques",
              "Automobilelektronik",
              "Werkzeugmaschinen",
              "Strukturfestigkeit von Schiffen und Offshore-Anlagen 2",
              "Internationale Rohstoffmärkte",
              "Angewandte numerische Strömungsmechanik",
              "Betriebsmittel der Hochspannungstechnik",
              "Information Mining",
              "Digitale Schaltungstechnik",
              "Technische Grundlagen zukünftiger Fahrzeugsysteme",
              "Rechnergestützte Netzanalysen",
              "Numerische Berechnungsmethoden für inkombressible Strömungen 1",
              "Testing of Metallic Materials Lab",
              "Numerische Berechnungsmethoden für inkombressible Strömungen 2",
              "Bordnetze",
              "Information Engineering",
              "Stahlbau 6 - Sonderkapitel des Stahlbaus",
              "OFDM-Übertragungstechnik",
              "Distributed Systems",
              "Entwurf von Schiffen und Offshore-Anlagen 2",
              "Prozesssimulation in der Metallurgie und Umformtechnik Praktikum",	
              "Hochspannungsgleichstromübertragung",
              "Strömungslehre 2",
              "Information Retrieval",
              "Advanced Modeling and Simulation Techniques",
              "Fehlerdiagnose und Fehlertoleranz in technischen Systemen",
              "Global Engineering Lab",
              "Moderne Energiesysteme",
              "Werkstoffauswahl für Hochtemperatureinsatz und Leichtbau",
              "Sicherheit und Risikoanalyse von Schiffen und Offshore-Anlagen"	,
              "Wärmebehandlung metallischer Werkstoffe Praktikum"	,
              "Turbulent Flows (Turbulente Strömungen)"	,
              "Hochspannungsmess- und Prüftechnik",
              "Wissensbasierte Systeme"	,
              "Finite Element Method - Modelling Concrete Structures",
              "MATLAB for Communications",
              "Elektronische Schaltungen Praktikum",
              "Multibody Dynamics",
              "Strategische Logistikplanung (alt: Außerbetrieblicher Transport)",
              "Wellentheorie und Welleninduzierte Lasten",
              "Metallkunde und Metallphysik Praktikum",
              "Sustainable Water Management",
              "Photovoltaik",
              "Advanced Image Synthesis",
              "Effective Properties of Micro-Heterogenous Materials",
              "Übertragungstechnik",
              "Entwurf digitaler Systeme für FPGAs Praktikum",		
              "Anlagenplanung und Systemtechnik",
              "Flachwasserhydrodynamik",
              "Plastomechanik und Umformverfahren Praktikum",
              "Siedlungswasserwirtschaft - Urban Water Supply Distribution",
              "Hochspannungstechnik  Praktikum",
              "Modelling and Simulation of Dynamic Systems Lab"	,
              "Scientific Visualization",
              "Pre-stressed Concrete",
              "Systemtechnik und Systemoptimierung",
              "Manövrieren von Schiffen",
              "Practical Course Water Technology",
              "Power System Operation and Control Lab",
              "Regelungstechnisches Aufbaupraktikum",
              "Computer Graphics",
              "Nonlinear Finite Element Method",	
              "Air Pollution Control",
              "Methoden der Systemtechnik",
              "Dynamik des Segelns und Gleitens",
              "Recycling of Oxidic and Metallic Materials Lab",
              "Wassertechnologie in der Praxis",
              "Nonlinear Control Systems Lab",
              "Gestaltung interaktiver Lehr-/Lernsysteme",
              "Objektorientierte Methoden der Modellbildung und Simulation",
              "Microwave Theory and Techniques Lab",
              "Robotik-Anwendungen",
              "Industrial Engineering",
              "Hafenwirtschaft und Logistik",
              "Mechanical and Biological Waste Treatment Exkursion MTW3",	
              "Operationsverstärker Praktikum",
              "Advanced Web Technologies",
              "Antennas for Communications",
              "Prozesssimulation in der Metallurgie und Umformtechnik",		
              "Learning Analytics",
              "Praxisprojekt Nachrichtentechnik",
              "Konstruieren mit Kunststoffen (alt: Kunststofftechnologie)",	
              "Turboverdichter",
              "Additive Fertigungsverfahren 3 - Metallverarbeitung",
              "Entwurf von Unterwasserfahrzeugen",
              "Investition und Kostenrechnung",
              "Masterseminar",
              "Computational Electromagnetics 1",
              "Computer Application in Metallurgy and Metal Forming",	
              "Computational Electromagnetics 2",			
              "Chemische Thermodynamik",
              "Elektrische Anlagen an Bord von Schiffen",			
              "Analysis of Structures",
              "Analoge Funksysteme",	
              "Informationstechniken zur Wissensintegration in Engineering-Prozesse",	
              "Schiffsschwingungen",
              "CAD in Civil Engineering",
              "Terahertz Technology",		
              "Zwei- und dreidimensionale Tragwerke",		
              "Computer Languages for Engineers",	
              "Thermodynamik für Fortgeschrittene (nur noch Wiederholer)",	
              "Anwendungsprogrammierung im Cax-Umfeld",	
              "Thermische Systeme: Analyse, Modellierung und Design",				
              "Absorption",
              "Virtuelle Produktoptimierung",	
              "Control Theory Lab",	
              "Numerics and Flow Simulation",									
              "Advanced Structural Analysis using ANSYS",									
              "Finite Element Method - Coupled Problems",										
              "Schwingungsanalyse mit MATLAB Lab",						
              "Combustion Science"	
            ]
            }, 
            {
              type:"rating",
              name: "gpa-most-liked-master",
              visibleIf: "{Major}=Master",
              title: "Please select the grade you have achieved in the course you liked the most.",
              isRequired: true,
            }, 
            {
              name: "most-disliked-master",
              title: "Please name a course which you disliked the most.",
              type: "text",
              isRequired: true,
              visibleIf: "{Major}=Master",
              choices: 
              [ 
                "Modellierung nebenläufiger Systeme",	
                "Geotechnik 7 - Numerische Modellierung in der Geotechnik",		
                "Mess- und Sensorsysteme",
                "Combustion Science (nur noch Wiederholer)",	
                "Combustion Science",	
                "Thermodynamik und Kinetik metallurgischer Reaktionen",	
                "Siedlungswasserwirtschaft 5 - Biologie und Chemie in der Siedlungswasserwirtschaft",	
                "Schaltanlagen",
                "Modellierung, Analyse, Verifikation",		
                "State and Parameter Estimation",
                "Mobilkommunikationsgeräte",
                "Manipulatortechnik",
                "Technische Schadenskunde",
                "Quality Management in Water Supply",
                "Regenerative Energietechnik 1",
                "Real-Time Systems (letztmalig im WiSe 19/20- nur noch Wiederholer)",	
                "Recommender Systeme	Advanced Numerical Methods",
                "Kommunikationsnetze	Optische Signalverarbeitung",		
                "Rechnergestützte Netzanalysen",
                "Strömungsmaschinen",
                "Testing of Metallic Materials",
                "Mechanische Verfahrenstechnik in der Wasseraufbereitung",
                "Mathematik E4",
                "Formale Spezifikation von Software-Systemen",
                "Geotechnik 4" ,
                "Bodenmechanik 2",					
                "Intermodale Distributionsnetze",
                "Regenerative Energietechnik 2",	
                "Die Methode der Finiten Elemente 1",	
                "Thermische Verfahrens- und Prozesstechnik",	
                "Advanced Computer Architecture",
                "Nonlinear Control Systems",		
                "Muster- und komponentenbasierte Software-Entwicklung",			
                "Bildsignaltechnik",				
                "Strategische Logistikplanung (alt: Außerbetrieblicher Transport)",	
                "Brennstoffzellensysteme in der dezentralen Energieversorgung",	
                "Endabmessungsnahes Gießen",	
                "Production Management",	
                "Leistungselektronik",
                "Natürlichsprachliche Mensch-Computer Interaktion",								
                "Quantitative bildgebende Messtechniken in Strömungen",	
                "Die Methode der Finiten Elemente 2",	
                "Adsorption Technology",	
                "Informationstechnik in der elektrischen Energietechnik",
                "Entwicklung sicherer Software	Continuum Mechanics",		
                "Systemtechnik (alt: Mikro- und Nanosystemtechnik)",			
                "Antriebstechnik",		
                "Fahrzeugtechnik",
                "Rechnerintegrierte Produktentwicklung CAE (Computer Aided Engineering)",	
                "Planung wassertechnischer Anlagen: Systemkomponenten, Instrumentierung und Steuerungstechnik",	
                "Netzberechnung",
                "Electronic communities and social networks",	
                "Introduction to Numerical Methods",	
                "Computer/Robot Vision	Optical Communications Technology",				
                "Fabrikplanung",		
                "Schweißtechnische Fertigungsverfahren",	
                "Energie und Umwelt",	
                "Elektromagnetische  Verträglichkeit",
                "Peer-to-Peer Systeme",	
                "Structural Dynamics Coding Theory",	
                "Test und Zuverlässigkeit digitaler Systeme",		
                "Dampfturbinen	Fahrzeugdynamik",			
                "Konstruieren mit Guss aus Fe- und NE-Metallen",
                "Siedlungswasserwirtschaft 4 - Stadtentwässerung und Regenwasserbehandlung",	
                "Nichtstationäre Vorgänge in elektrischen Netzen",
                "Mehrgrößenregelung",			
                "Design of concrete structures",		
                "Internet of Things: Protocols and System Software",			
                "Biomechanik	Höhere Werkstofftechnik - Tribologie",		
                "Metallkunde und Metallphysik",
                "Waste Water Treatment",	
                "Theorie statistischer Signale",
                "Interaktive Systeme",		
                "Robust Control (Robuste Regelung)",				
                "Biofluidmechanik",	
                "Automobile Produktionstechnik",	
                "Tensor Calculus",
                "Thermische Abfallbehandlung",	
                "Modelling and Simulation of Dynamic Systems",
                "Cognitive Robot Systems",			
                "Numerical Mathematics",			
                "Notlauf und Diagnose mechatronischer Systeme",	
                "Informationssysteme der Logistik (alt: Logistische Informationssysteme)",	
                "Control Theory",	
                "Schwingungsanalyse metallurgischer Anlagen",	
                "Computational Fluid Dynamics (incompressible fluids)",	
                "Elektrizitätswirtschaft",
                "Advanced Mobile Communications",				
                "Modellierung von Logistiksystemen (alt: Rechnergestützte Modellierung)",	
                "Sensoren für Fortgeschrittene - Anwendungen, Schnittstellen und Signalverarbeitung",	
                "Gießen und Erstarren von Stahl",	
                "Water Treatment 2",	
                "Theoretische Elektrotechnik 1",
                "Thermodynamics of Materials",		
                "Self-Organising Embedded Systems",			
                "Kinematics of Robots and Mechanism",		
                "Verbrennungsmotoren",	
                "Werkstoffwissenschaftliche Vertiefung der Fe-Gusswerkstoffe",	
                "Water - Natural Science Fundamentals",	
                "Numerical  Mathematics",
                "Neuroinformatik und Organic Computing",	
                "Stahlbau 5 - Schalen, Türme und Masten aus Stahl",	
                "Theoretische Elektrotechnik 2",	
                "Radio Propagation Channels",			
                "Qualitative Methoden der Regelungstechnik 2: Automaten und Netze",	
                "Kunststoffmaschinen und -verarbeitung: Spritzgießtechnik",	
                "Thermische Verfahrenstechnik",	
                "Recycling of Oxidic and Metallic Materials",	
                "Wassergewinnung",	
                "Thermodynamik und Kraftwerktechnik",		
                "Game Architecture and Design",	
                "Finite Element Method - Multiphase Materials",		
                "Global Engineering",			
                "Schwingungsanalyse mit MATLAB",	
                "Virtuelle Produktdarstellung",	
                "Wärmebehandlung metallischer Werkstoffe",	
                "Management und Controlling in der Wasserversorgung und -entsorgung",	
                "Power System Operation and Control",
                "Cloud, Web&Mobile",
                "Elektronische Schaltungen",	
                "Kognitive Technische Systeme",
                "Hydrodynamik 2",
                "Plastomechanik und Umformverfahren",
                "Water Treatment 1",
                "Grundlagen der Hochspannungstechnik",
                "Computational Inelasticity",
                "Advanced System and Control Theory",
                "Hochfrequenzschaltungen und Leistungsbauelemente",	
                "Gasturbinen",
                "Additive Fertigungsverfahren 2 – Kunststoffverarbeitung",
                "Seeverhalten und hydrodynamische Belastung von Schiffen und Offshore-Anlagen",	
                "Wärme- und Stoffübertragung",
                "Membrane Technology for Water Treatment",
                "Wind Energy",
                "Prozessautomatisierung",
                "Finite Element Method Foundation",
                "Microwave Theory and Techniques",
                "Automobilelektronik",
                "Werkzeugmaschinen",
                "Strukturfestigkeit von Schiffen und Offshore-Anlagen 2",
                "Internationale Rohstoffmärkte",
                "Angewandte numerische Strömungsmechanik",
                "Betriebsmittel der Hochspannungstechnik",
                "Information Mining",
                "Digitale Schaltungstechnik",
                "Technische Grundlagen zukünftiger Fahrzeugsysteme",
                "Rechnergestützte Netzanalysen",
                "Numerische Berechnungsmethoden für inkombressible Strömungen 1",
                "Testing of Metallic Materials Lab",
                "Numerische Berechnungsmethoden für inkombressible Strömungen 2",
                "Bordnetze",
                "Information Engineering",
                "Stahlbau 6 - Sonderkapitel des Stahlbaus",
                "OFDM-Übertragungstechnik",
                "Distributed Systems",
                "Entwurf von Schiffen und Offshore-Anlagen 2",
                "Prozesssimulation in der Metallurgie und Umformtechnik Praktikum",	
                "Hochspannungsgleichstromübertragung",
                "Strömungslehre 2",
                "Information Retrieval",
                "Advanced Modeling and Simulation Techniques",
                "Fehlerdiagnose und Fehlertoleranz in technischen Systemen",
                "Global Engineering Lab",
                "Moderne Energiesysteme",
                "Werkstoffauswahl für Hochtemperatureinsatz und Leichtbau",
                "Sicherheit und Risikoanalyse von Schiffen und Offshore-Anlagen",
                "Wärmebehandlung metallischer Werkstoffe Praktikum",
                "Turbulent Flows (Turbulente Strömungen)",
                "Hochspannungsmess- und Prüftechnik",
                "Wissensbasierte Systeme",
                "Finite Element Method - Modelling Concrete Structures",
                "MATLAB for Communications",
                "Elektronische Schaltungen Praktikum",
                "Multibody Dynamics",
                "Strategische Logistikplanung (alt: Außerbetrieblicher Transport)",
                "Wellentheorie und Welleninduzierte Lasten",
                "Metallkunde und Metallphysik Praktikum",
                "Sustainable Water Management",
                "Photovoltaik",
                "Advanced Image Synthesis",
                "Effective Properties of Micro-Heterogenous Materials",
                "Übertragungstechnik",
                "Entwurf digitaler Systeme für FPGAs Praktikum",		
                "Anlagenplanung und Systemtechnik",
                "Flachwasserhydrodynamik",
                "Plastomechanik und Umformverfahren Praktikum",
                "Siedlungswasserwirtschaft - Urban Water Supply Distribution",
                "Hochspannungstechnik  Praktikum",
                "Modelling and Simulation of Dynamic Systems Lab",
                "Scientific Visualization",
                "Pre-stressed Concrete",
                "Systemtechnik und Systemoptimierung",
                "Manövrieren von Schiffen",
                "Practical Course Water Technology",
                "Power System Operation and Control Lab",
                "Regelungstechnisches Aufbaupraktikum",
                "Computer Graphics",
                "Nonlinear Finite Element Method",	
                "Air Pollution Control",
                "Methoden der Systemtechnik",
                "Dynamik des Segelns und Gleitens",
                "Recycling of Oxidic and Metallic Materials Lab",
                "Wassertechnologie in der Praxis",
                "Nonlinear Control Systems Lab"	,
                "Gestaltung interaktiver Lehr-/Lernsysteme",
                "Objektorientierte Methoden der Modellbildung und Simulation",
                "Microwave Theory and Techniques Lab",
                "Robotik-Anwendungen",
                "Industrial Engineering",
                "Hafenwirtschaft und Logistik",
                "Mechanical and Biological Waste Treatment	Exkursion MTW3",	
                "Operationsverstärker Praktikum",
                "Advanced Web Technologies",
                "Antennas for Communications",
                "Prozesssimulation in der Metallurgie und Umformtechnik",		
                "Learning Analytics",
                "Praxisprojekt Nachrichtentechnik",
                "Konstruieren mit Kunststoffen (alt: Kunststofftechnologie)",	
                "Turboverdichter",
                "Additive Fertigungsverfahren 3 - Metallverarbeitung",
                "Entwurf von Unterwasserfahrzeugen",
                "Investition und Kostenrechnung",
                "Masterseminar",
                "Computational Electromagnetics 1",
                "Computer Application in Metallurgy and Metal Forming",	
                "Computational Electromagnetics 2",			
                "Chemische Thermodynamik",
                "Elektrische Anlagen an Bord von Schiffen",			
                "Analysis of Structures",
                "Analoge Funksysteme",	
                "Informationstechniken zur Wissensintegration in Engineering-Prozesse",	
                "Schiffsschwingungen",
                "CAD in Civil Engineering",
                "Terahertz Technology",		
                "Zwei- und dreidimensionale Tragwerke",		
                "Computer Languages for Engineers",	
                "Thermodynamik für Fortgeschrittene (nur noch Wiederholer)",	
                "Anwendungsprogrammierung im Cax-Umfeld",	
                "Thermische Systeme: Analyse, Modellierung und Design",				
                "Absorption",
                "Virtuelle Produktoptimierung",	
                "Control Theory Lab",	
                "Numerics and Flow Simulation",									
                "Advanced Structural Analysis using ANSYS",									
                "Finite Element Method - Coupled Problems",										
                "Schwingungsanalyse mit MATLAB Lab"
              ]
            }, 
            {
              type:"rating",
              name: "gpa-most-disliked-master",
              visibleIf: "{Major}=Master",
              title: "Please select the grade you have achieved in the course you disliked the most.",
              isRequired: true,
            },
            {
              type: "text",
              name: "country",
              title: "Please name your country.",
              isRequired: true,
              choices: 
              [
                  "Afghanistan",
                  "Akrotiri",
                  "Albania",
                  "Algeria",
                  "American Samoa",
                  "Andorra",
                  "Angola",
                  "Anguilla",
                  "Antarctica",
                  "Antigua and Barbuda",
                  "Argentina",
                  "Armenia",
                  "Aruba",
                  "Ashmore and Cartier Islands",
                  "Australia",
                  "Austria",
                  "Azerbaijan",
                  "Bahamas",
                  "Bahrain",
                  "Bangladesh",
                  "Barbados",
                  "Bassas da India",
                  "Belarus",
                  "Belgium",
                  "Belize",
                  "Benin",
                  "Bermuda",
                  "Bhutan",
                  "Bolivia",
                  "Bosnia and Herzegovina",
                  "Botswana",
                  "Bouvet Island",
                  "Brazil",
                  "British Indian Ocean Territory",
                  "British Virgin Islands",
                  "Brunei",
                  "Bulgaria",
                  "Burkina Faso",
                  "Burma",
                  "Burundi",
                  "Cambodia",
                  "Cameroon",
                  "Canada",
                  "Cape Verde",
                  "Cayman Islands",
                  "Central African Republic",
                  "Chad",
                  "Chile",
                  "China",
                  "Christmas Island",
                  "Clipperton Island",
                  "Cocos (Keeling) Islands",
                  "Colombia",
                  "Comoros",
                  "Democratic Republic of Congo",
                  "Cook Islands",
                  "Coral Sea Islands",
                  "Costa Rica",
                  "Cote d'Ivoire",
                  "Croatia",
                  "Cuba",
                  "Cyprus",
                  "Czech Republic",
                  "Denmark",
                  "Dhekelia",
                  "Djibouti",
                  "Dominica",
                  "Dominican Republic",
                  "Ecuador",
                  "Egypt",
                  "El Salvador",
                  "Equatorial Guinea",
                  "Eritrea",
                  "Estonia",
                  "Ethiopia",
                  "Europa Island",
                  "Falkland Islands (Islas Malvinas)",
                  "Faroe Islands",
                  "Fiji",
                  "Finland",
                  "France",
                  "French Guiana",
                  "French Polynesia",
                  "French Southern and Antarctic Lands",
                  "Gabon",
                  "Gambia",
                  "Gaza Strip",
                  "Georgia",
                  "Germany",
                  "Ghana",
                  "Gibraltar",
                  "Glorioso Islands",
                  "Greece",
                  "Greenland",
                  "Grenada",
                  "Guadeloupe",
                  "Guam",
                  "Guatemala",
                  "Guernsey",
                  "Guinea",
                  "Guinea-Bissau",
                  "Guyana",
                  "Haiti",
                  "Heard Island and McDonald Islands",
                  "Holy See (Vatican City)",
                  "Honduras",
                  "Hong Kong",
                  "Hungary",
                  "Iceland",
                  "India",
                  "Indonesia",
                  "Iran",
                  "Iraq",
                  "Ireland",
                  "Isle of Man",
                  "Israel",
                  "Italy",
                  "Jamaica",
                  "Jan Mayen",
                  "Japan",
                  "Jersey",
                  "Jordan",
                  "Juan de Nova Island",
                  "Kazakhstan",
                  "Kenya",
                  "Kiribati",
                  "Korea, North",
                  "Korea, South",
                  "Kuwait",
                  "Kyrgyzstan",
                  "Laos",
                  "Latvia",
                  "Lebanon",
                  "Lesotho",
                  "Liberia",
                  "Libya",
                  "Liechtenstein",
                  "Lithuania",
                  "Luxembourg",
                  "Macau",
                  "Macedonia",
                  "Madagascar",
                  "Malawi",
                  "Malaysia",
                  "Maldives",
                  "Mali",
                  "Malta",
                  "Marshall Islands",
                  "Martinique",
                  "Mauritania",
                  "Mauritius",
                  "Mayotte",
                  "Mexico",
                  "Micronesia",
                  "Moldova",
                  "Monaco",
                  "Mongolia",
                  "Montenegro",
                  "Montserrat",
                  "Morocco",
                  "Mozambique",
                  "Namibia",
                  "Nauru",
                  "Navassa Island",
                  "Nepal",
                  "Netherlands",
                  "Netherlands Antilles",
                  "New Caledonia",
                  "New Zealand",
                  "Nicaragua",
                  "Niger",
                  "Nigeria",
                  "Niue",
                  "Norfolk Island",
                  "Northern Mariana Islands",
                  "Norway",
                  "Oman",
                  "Pakistan",
                  "Palau",
                  "Panama",
                  "Papua New Guinea",
                  "Paracel Islands",
                  "Paraguay",
                  "Peru",
                  "Philippines",
                  "Pitcairn Islands",
                  "Poland",
                  "Portugal",
                  "Puerto Rico",
                  "Qatar",
                  "Reunion",
                  "Romania",
                  "Russia",
                  "Rwanda",
                  "Saint Helena",
                  "Saint Kitts and Nevis",
                  "Saint Lucia",
                  "Saint Pierre and Miquelon",
                  "Saint Vincent and the Grenadines",
                  "Samoa",
                  "San Marino",
                  "Sao Tome and Principe",
                  "Saudi Arabia",
                  "Senegal",
                  "Serbia",
                  "Seychelles",
                  "Sierra Leone",
                  "Singapore",
                  "Slovakia",
                  "Slovenia",
                  "Solomon Islands",
                  "Somalia",
                  "South Africa",
                  "South Georgia and the South Sandwich Islands",
                  "Spain",
                  "Spratly Islands",
                  "Sri Lanka",
                  "Sudan",
                  "Suriname",
                  "Svalbard",
                  "Swaziland",
                  "Sweden",
                  "Switzerland",
                  "Syria",
                  "Taiwan",
                  "Tajikistan",
                  "Tanzania",
                  "Thailand",
                  "Timor-Leste",
                  "Togo",
                  "Tokelau",
                  "Tonga",
                  "Trinidad and Tobago",
                  "Tromelin Island",
                  "Tunisia",
                  "Turkey",
                  "Turkmenistan",
                  "Turks and Caicos Islands",
                  "Tuvalu",
                  "Uganda",
                  "Ukraine",
                  "United Arab Emirates",
                  "United Kingdom",
                  "United States",
                  "Uruguay",
                  "Uzbekistan",
                  "Vanuatu",
                  "Venezuela",
                  "Vietnam",
                  "Virgin Islands",
                  "Wake Island",
                  "Wallis and Futuna",
                  "West Bank",
                  "Western Sahara",
                  "Yemen",
                  "Zambia",
                  "Zimbabwe"
                ]
            }, 
            {
              type: "radiogroup",
              name: "gender",
              title: "Please state your gender.",
              isRequired: true,
              colCount: 3,
              choices: 
                [
                  "Male",
                  "Female",
                  "Other"
                ]
            }, 
            {
              type: "radiogroup",
              name: "* requiered fields"
            }
          ]
        } 
    ]
};

export default FindYourType;