# Generated by Django 4.2.3 on 2023-07-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E3Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('catalog', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('sws', models.CharField(max_length=255)),
                ('num_expected_participants', models.CharField(max_length=255)),
                ('max_participants', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timetables', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('exam_type', models.CharField(max_length=255)),
                ('ausgeschlossen_ingenieurwissenschaften_bachelor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='E3StudyPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='E3Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairness', models.FloatField()),
                ('support', models.FloatField()),
                ('material', models.FloatField()),
                ('fun', models.FloatField()),
                ('comprehensibility', models.FloatField()),
                ('interesting', models.FloatField()),
                ('grade_effort', models.FloatField()),
                ('e3_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_e3selector.e3course')),
            ],
        ),
        migrations.AddField(
            model_name='e3course',
            name='e3_study_programs',
            field=models.ManyToManyField(to='app_e3selector.e3studyprograms'),
        ),
    ]
