# Generated by Django 4.2.7 on 2023-11-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_e3selector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e3course',
            name='timetables',
            field=models.TextField(),
        ),
    ]
