apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: 2-api-gateway
  app.kubernetes.io/part-of: backend

resources:
- deployment.yaml
- service.yaml
