apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend-2-api-gateway

resources:
- deployment.yaml
- service.yaml

vars:
- name: BACKEND_2_API_GATEWAY_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: 2-api-gateway
