apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend-4-e3selector-web

resources:
- deployment.yaml
- service.yaml

vars:
- name: BACKEND_4_E3SELECTOR_WEB_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: web
