services:
  proxy:
    image: ${IMAGE_NAME_PREFIX:-socialcomputing/}elas-official-proxy:${IMAGE_TAG:-latest}
    build: .
    ports:
    - 8001:8000
    restart: always
    depends_on:
      frontend:
        condition: service_started
      backend-2-api-gateway:
        condition: service_started # service_healthy
