apiVersion: apps/v1
kind: Deployment
metadata:
  name: 4-e3selector
  labels:
    app.kubernetes.io/component: 4-e3selector
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: 4-e3selector
  template:
    metadata:
      labels:
        app.kubernetes.io/component: 4-e3selector
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: web
        image: socialcomputing/elas-official-backend-4-e3selector
        ports:
        - containerPort: 8004
        env:
        - name: PORT
          value: 8004
        - name: EUREKA_HOST_NAME
          value: $(1_SERVICE_REGISTRY_SERVICE)
        - name: EUREKA_PORT
          value: 8761
