apiVersion: v1
kind: Service
metadata:
  name: "frontend"
  labels:
    app.kubernetes.io/component: "frontend"
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: "frontend"
