apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: leader
        image: redis
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        ports:
        - containerPort: 6379
