apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend-4-e3selector-redis

resources:
- deployment.yaml
- service.yaml

vars:
- name: BACKEND_4_E3SELECTOR_REDIS_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: redis
