name: Continuous Integration

on:
  push:
    tags:       [ v*.*.* ]
    branches:   [ master, main ]
  pull_request:
    branches:   [ master, main ]

jobs:
  images:
    uses: ./.github/workflows/build.yml
    with:
      services:        "[ 'backend/1-service-registry', 'backend/2-api-gateway', 'backend/3-auth', 'backend/4-e3selector', 'backend/5-studycompass', 'frontend' ]"
      base_image_name: "socialcomputing/elas-official-"
      push:            ${{ github.event_name != 'pull_request' }}
    secrets:
      registry_user:   ${{ secrets.DOCKERHUB_USERNAME }}
      registry_token:  ${{ secrets.DOCKERHUB_TOKEN }}

  release:
    needs: [ images ]
    if:    github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    uses:  ./.github/workflows/release.yml
